Hendry_Auto.Web/Areas/Admin/Controllers/VehicleTypeController.cs
using Hendry_Auto.Application.ApplicationConstants;
using Hendry_Auto.Application.Contracts.Persistence;
using Hendry_Auto.Domain.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Hendry_Auto.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = CustomRole.MasterAdmin + "," + CustomRole.Admin)]
    public class VehicleTypeController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public VehicleTypeController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            List<VehicleType> vehicleTypes = await _unitOfWork.VehicleType.GetAllAsync();
            return View(vehicleTypes);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(VehicleType vehicleType)
        {
            if (ModelState.IsValid)
            {
                await _unitOfWork.VehicleType.Create(vehicleType);
                await _unitOfWork.SaveAsync();
                TempData["success"] = CommonMessage.RecordCreated;
                return RedirectToAction(nameof(Index));
            }
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            VehicleType vehicleType = await _unitOfWork.VehicleType.GetByIdAsync(id);
            if (vehicleType == null)
            {
                return NotFound();
            }
            return View(vehicleType);
        }
        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            VehicleType vehicleType = await _unitOfWork.VehicleType.GetByIdAsync(id);
            if (vehicleType == null)
            {
                return NotFound();
            }
            return View(vehicleType);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(VehicleType vehicleType)
        {
            if (ModelState.IsValid)
            {
                await _unitOfWork.VehicleType.Update(vehicleType);
                await _unitOfWork.SaveAsync();
                TempData["success"] = CommonMessage.RecordUpdated;
                return RedirectToAction(nameof(Index));
            }
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            VehicleType vehicleType = await _unitOfWork.VehicleType.GetByIdAsync(id);
            if (vehicleType == null)
            {
                return NotFound();
            }
            return View(vehicleType);
        }
        [HttpPost]
        public async Task<IActionResult> Delete(VehicleType vehicleType)
        {
            await _unitOfWork.VehicleType.Delete(vehicleType);
            await _unitOfWork.SaveAsync();
            TempData["success"] = CommonMessage.RecordDeleted;
            return RedirectToAction(nameof(Index));           
        }
    }
}

Hendry_Auto.Web/Areas/Admin/Views/VehicleType/Create.cshtml
@model VehicleType

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2 class="text-uppercase text-center">Create Vehicle Type</h2>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12 border border-1">
            <form method="post" enctype="multipart/form-data">
                <div class="mb-3">
                    <label asp-for="@Model.Name" class="form-label"></label>
                    <input asp-for="@Model.Name" class="form-control" />
                    <span asp-validation-for="@Model.Name" class="text-danger"></span>
                </div>  
                
                <div class="mb-3">
                    <a asp-area="Admin" asp-controller="VehicleType" asp-action="Index" class="btn btn-danger">Back</a>
                    <button type="submit" class="btn btn-success">Create</button>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />

}

Hendry_Auto.Web/Areas/Admin/Views/VehicleType/Delete.cshtml
@model VehicleType

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2 class="text-uppercase text-center">Delete Vehicle Type</h2>
        </div>
    </div>

    <div class="row">
        <div class="col-md-8 border border-1">
            <form method="post" enctype="multipart/form-data">
                <input asp-for="@Model.Id" hidden />
                
                <div class="mb-3">
                    <label asp-for="@Model.Name" class="form-label"></label>
                    <input asp-for="@Model.Name" class="form-control" disabled/>
                    
                </div>                              

                <div class="mb-3">
                    <a asp-area="Admin" asp-controller="VehicleType" asp-action="Index" class="btn btn-danger">Back</a>
                    <button type="submit" class="btn btn-danger">Delete</button>
                </div>
            </form>
        </div>        
    </div>
</div>

Hendry_Auto.Web/Areas/Admin/Views/VehicleType/Details.cshtml
@model VehicleType

<div class="container">
    <div class="card">
        <div class="card-header text-center text-uppercase">
            Vehicle Type Details
        </div>

        <div class="card-body">
            <div class="row">
                <div class="col-md-8">
                    <div class="row">
                        <div class="col-md-4">
                            <p class="card-text text-uppercase"><strong>Id</strong></p>
                        </div>
                        <div class="col-md-8">
                            <p class="card-text">@Model.Id</p>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-4">
                            <p class="card-text text-uppercase"><strong>Vehicle Type Name</strong></p>
                        </div>
                        <div class="col-md-8">
                            <p class="card-text">@Model.Name</p>
                        </div>
                    </div>                    
                </div>               
            </div>

            <div class="row">
                <div class="col-md-12 text-center">
                    <a asp-area="Admin" asp-controller="VehicleType" asp-action="Index" class="btn btn-danger">Back</a>
                </div>
            </div>
        </div>
    </div>
</div>

Hendry_Auto.Web/Areas/Admin/Views/VehicleType/Edit.cshtml
@model VehicleType

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2 class="text-uppercase text-center">Edit Vehicle Type</h2>
        </div>
    </div>

    <div class="row">
        <div class="col-md-8 border border-1">
            <form method="post" enctype="multipart/form-data">
                <div class="mb-3">
                    <label asp-for="@Model.Name" class="form-label"></label>
                    <input asp-for="@Model.Name" class="form-control" />
                    <span asp-validation-for="@Model.Name" class="text-danger"></span>
                </div>


                <div class="mb-3">
                    <a asp-area="Admin" asp-controller="VehicleType" asp-action="Index" class="btn btn-danger">Back</a>
                    <button type="submit" class="btn btn-warning">Update</button>
                </div>
            </form>
        </div>        
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />

}

Hendry_Auto.Web/Areas/Admin/Views/VehicleType/Index.cshtml
@model List<VehicleType>

@{
    int count = 0;
}

<div class="container">
    <div class="row mb-4">
        <div class="col-md-6 text-uppercase">
            <h2>Vehicle Type List</h2>
        </div>
        <div class="col-md-6 text-end">
            <a asp-area="Admin" asp-controller="VehicleType" asp-action="Create" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i> Create
            </a>
        </div>
    </div>
    <hr />

    @if (Model != null && Model.Any())
    {
        <table id="table" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th class="text-center">S. No</th>
                    <th class="text-center">Vehicle Type</th>
                    
                    <th class="text-center">Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td class="text-center" width="20%">@(++count)</td>
                        <td  width="60%">@item.Name</td>
                        
                        <td class="text-center">
                            <div class="btn-group" role="group">
                                <a asp-area="Admin" asp-controller="VehicleType"
                                   asp-action="Details"
                                   asp-route-id="@item.Id"
                                   class="btn btn-info btn-sm"
                                   data-bs-toggle="tooltip"
                                   data-bs-placement="top"
                                   title="View details">
                                    <i class="bi bi-info-circle"></i> Details
                                </a>
                                <a asp-area="Admin" asp-controller="VehicleType"
                                   asp-action="Edit"
                                   asp-route-id="@item.Id"
                                   class="btn btn-warning btn-sm"
                                   data-bs-toggle="tooltip"
                                   data-bs-placement="top"
                                   title="View details">
                                    <i class="bi bi-pencil-square"></i> Update
                                </a>
                                <a asp-area="Admin" asp-controller="VehicleType"
                                   asp-action="Delete"
                                   asp-route-id="@item.Id"
                                   class="btn btn-danger btn-sm"
                                   data-bs-toggle="tooltip"
                                   data-bs-placement="top"
                                   title="View details">
                                    <i class="bi bi-trash"></i> Delete
                                </a>
                            </div>
                            
                        </td>
                        
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h2 class="text-center text-uppercase text-warning pt-4">
                        No Brands Found
                    </h2>
                </div>
            </div>
        </div>
    }
</div>

@section Scripts{
    <script>
        $('.table').DataTable();
    </script>
}