Hendry_Auto.Web/Areas/Admin/Controllers/PostController.cs
using Hendry_Auto.Application.ApplicationConstants;
using Hendry_Auto.Application.Contracts.Persistence;
using Hendry_Auto.Application.Services.Interface;
using Hendry_Auto.Domain.ApplicationEnums;
using Hendry_Auto.Domain.Models;
using Hendry_Auto.Domain.ViewModel;
using Hendry_Auto.Infrastructure.Migrations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Hosting;



namespace Hendry_Auto.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = CustomRole.MasterAdmin + "," + CustomRole.Admin)]
    public class PostController : Microsoft.AspNetCore.Mvc.Controller
    {
        private readonly IUnitOfWork _UnitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IUserNameService _userNameService;
        public PostController(IUnitOfWork UnitOfWork, IWebHostEnvironment webHostEnvironment, IUserNameService userNameService)
        {
            _UnitOfWork = UnitOfWork;
            _webHostEnvironment = webHostEnvironment;
            _userNameService = userNameService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            List<Domain.Models.Post> Posts =await _UnitOfWork.Post.GetAllPost();
            return View(Posts);
        }
        [HttpGet]
        public IActionResult Create()
        {
            IEnumerable<SelectListItem> BrandList = _UnitOfWork.Brand.Query().Select(x => new SelectListItem
            {
                Text = x.Name.ToUpper(),
                Value = x.Id.ToString()
            });

            IEnumerable<SelectListItem> VehicleTypeList = _UnitOfWork.VehicleType.Query().Select(x => new SelectListItem
            {
                Text = x.Name.ToUpper(),
                Value = x.Id.ToString()
            });

            IEnumerable<SelectListItem> EngineAndFuelTypeList = Enum.GetValues(typeof(EngineAndFuelType)).Cast<EngineAndFuelType>().Select(x => new SelectListItem
            {
                Text = x.ToString().ToUpper(),
                Value = ((int)x).ToString()
            });

            IEnumerable<SelectListItem> TransmissionList = Enum.GetValues(typeof(Transmission)).Cast<Transmission>().Select(x => new SelectListItem
            {
                Text = x.ToString().ToUpper(),
                Value = ((int)x).ToString()
            });


            PostVM postVM = new PostVM
            {
                Post = new Domain.Models.Post(),
                BrandList = BrandList,
                VehicleTypeList = VehicleTypeList,
                EngineAndFuelTypeList = EngineAndFuelTypeList,
                TransmissionList = TransmissionList
            };                
                
            return View(postVM);
        }
        [HttpPost]
        public async Task<IActionResult> Create(PostVM PostVM)
        {
            string WebRootPath = _webHostEnvironment.WebRootPath;

            var file = HttpContext.Request.Form.Files;

            if(file.Count>0)
            {
                string newFileName = Guid.NewGuid().ToString();
                var upload = Path.Combine(WebRootPath, @"images\Post");
                var extention = Path.GetExtension(file[0].FileName);
                using(var fileStream = new FileStream(Path.Combine(upload, newFileName + extention), FileMode.Create))
                {
                    file[0].CopyTo(fileStream);
                }
                PostVM.Post.VehicleImage = @"\images\Post\" + newFileName + extention;

            }
            if(ModelState.IsValid)
            {
                await _UnitOfWork.Post.Create(PostVM.Post);
                await _UnitOfWork.SaveAsync();
                TempData["Success"] = CommonMessage.RecordCreated;
                return RedirectToAction(nameof(Index));
            }
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            Domain.Models.Post Post = await _UnitOfWork.Post.GetPostById(id);
            Post.CreatedBy = await _userNameService.GetUserName(Post.CreatedBy);
            Post.ModifiedBy = await _userNameService.GetUserName(Post.ModifiedBy);
            if (Post == null)
            {
                return NotFound();
            }
            return View(Post);
        }
        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            Domain.Models.Post Post = await _UnitOfWork.Post.GetPostById(id);
            IEnumerable<SelectListItem> BrandList = _UnitOfWork.Brand.Query().Select(x => new SelectListItem
            {
                Text = x.Name.ToUpper(),
                Value = x.Id.ToString()
            });

            IEnumerable<SelectListItem> VehicleTypeList = _UnitOfWork.VehicleType.Query().Select(x => new SelectListItem
            {
                Text = x.Name.ToUpper(),
                Value = x.Id.ToString()
            });

            IEnumerable<SelectListItem> EngineAndFuelTypeList = Enum.GetValues(typeof(EngineAndFuelType)).Cast<EngineAndFuelType>().Select(x => new SelectListItem
            {
                Text = x.ToString().ToUpper(),
                Value = ((int)x).ToString()
            });

            IEnumerable<SelectListItem> TransmissionList = Enum.GetValues(typeof(Transmission)).Cast<Transmission>().Select(x => new SelectListItem
            {
                Text = x.ToString().ToUpper(),
                Value = ((int)x).ToString()
            });

            PostVM postVM = new PostVM
            {
                Post = Post,
                BrandList = BrandList,
                VehicleTypeList = VehicleTypeList,
                EngineAndFuelTypeList = EngineAndFuelTypeList,
                TransmissionList = TransmissionList
            };

            return View(postVM);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(PostVM PostVM)
        {
            string WebRootPath = _webHostEnvironment.WebRootPath;
            var file = HttpContext.Request.Form.Files;
            if (file.Count > 0)
            {
                string newFileName = Guid.NewGuid().ToString();
                var upload = Path.Combine(WebRootPath, @"images\Post");
                var extention = Path.GetExtension(file[0].FileName);

                // Delete old file if it exists
                var objFromDb = await _UnitOfWork.Post.GetByIdAsync(PostVM.Post.Id);

                if(objFromDb.VehicleImage != null)
                {
                    var oldImagePath = Path.Combine(WebRootPath, objFromDb.VehicleImage.Trim('\\'));
                    if (System.IO.File.Exists(oldImagePath))
                    {
                        System.IO.File.Delete(oldImagePath);
                    }
                }

                using (var fileStream = new FileStream(Path.Combine(upload, newFileName + extention), FileMode.Create))
                {
                    file[0].CopyTo(fileStream);
                }
                PostVM.Post.VehicleImage = @"\images\Post\" + newFileName + extention;
            }
            if (ModelState.IsValid)
            {
                await _UnitOfWork.Post.Update(PostVM.Post);
                await _UnitOfWork.SaveAsync();
                
                TempData["Warning"] = CommonMessage.RecordUpdated;
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            Domain.Models.Post Post = await _UnitOfWork.Post.GetPostById(id);
            IEnumerable<SelectListItem> BrandList = _UnitOfWork.Brand.Query().Select(x => new SelectListItem
            {
                Text = x.Name.ToUpper(),
                Value = x.Id.ToString()
            });

            IEnumerable<SelectListItem> VehicleTypeList = _UnitOfWork.VehicleType.Query().Select(x => new SelectListItem
            {
                Text = x.Name.ToUpper(),
                Value = x.Id.ToString()
            });

            IEnumerable<SelectListItem> EngineAndFuelTypeList = Enum.GetValues(typeof(EngineAndFuelType)).Cast<EngineAndFuelType>().Select(x => new SelectListItem
            {
                Text = x.ToString().ToUpper(),
                Value = ((int)x).ToString()
            });

            IEnumerable<SelectListItem> TransmissionList = Enum.GetValues(typeof(Transmission)).Cast<Transmission>().Select(x => new SelectListItem
            {
                Text = x.ToString().ToUpper(),
                Value = ((int)x).ToString()
            });

            PostVM postVM = new PostVM
            {
                Post = Post,
                BrandList = BrandList,
                VehicleTypeList = VehicleTypeList,
                EngineAndFuelTypeList = EngineAndFuelTypeList,
                TransmissionList = TransmissionList
            };
            return View(postVM);
        }
        [HttpPost]
        public async Task<IActionResult> Delete(PostVM PostVM)
        {
            string WebRootPath = _webHostEnvironment.WebRootPath;
            if(!string.IsNullOrEmpty(PostVM.Post.VehicleImage))
            {
                // Delete old file if it exists
                var objFromDb = await _UnitOfWork.Post.GetByIdAsync(PostVM.Post.Id);

                if (objFromDb.VehicleImage != null)
                {
                    var oldImagePath = Path.Combine(WebRootPath, objFromDb.VehicleImage.Trim('\\'));
                    if (System.IO.File.Exists(oldImagePath))
                    {
                        System.IO.File.Delete(oldImagePath);
                    }
                }

            }
            await _UnitOfWork.Post.Delete(PostVM.Post);
            await _UnitOfWork.SaveAsync();
            TempData["Error"] = CommonMessage.RecordDeleted;
            return RedirectToAction(nameof(Index));
        }
    }
}

Hendry_Auto.Web/Controllers/BrandController.cs
using Hendry_Auto.Domain.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Hendry_Auto.Infrastructure.Common;
using Hendry_Auto.Application.ApplicationConstants;
using Hendry_Auto.Application.Contracts.Persistence;
using System.Threading.Tasks;

namespace Hendry_Auto.Web.Controllers
{
    public class BrandController : Controller
    {
        private readonly IUnitOfWork _UnitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public BrandController(IUnitOfWork UnitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _UnitOfWork = UnitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            List<Brand> brands =await _UnitOfWork.Brand.GetAllAsync();
            return View(brands);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Brand brand)
        {
            string WebRootPath = _webHostEnvironment.WebRootPath;

            var file = HttpContext.Request.Form.Files;

            if(file.Count>0)
            {
                string newFileName = Guid.NewGuid().ToString();
                var upload = Path.Combine(WebRootPath, @"images\brand");
                var extention = Path.GetExtension(file[0].FileName);
                using(var fileStream = new FileStream(Path.Combine(upload, newFileName + extention), FileMode.Create))
                {
                    file[0].CopyTo(fileStream);
                }
                brand.BrandLogo = @"\images\brand\" + newFileName + extention;

            }
            if(ModelState.IsValid)
            {
                await _UnitOfWork.Brand.Create(brand);
                await _UnitOfWork.SaveAsync();
                TempData["Success"] = CommonMessage.RecordCreated;
                return RedirectToAction(nameof(Index));
            }
            return View(brand);
        }
        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            Brand brand = await _UnitOfWork.Brand.GetByIdAsync(id);
            if (brand == null)
            {
                return NotFound();
            }
            return View(brand);
        }
        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            Brand brand = await _UnitOfWork.Brand.GetByIdAsync(id);
            if(brand == null)
            {
                return NotFound();
            }
            return View(brand);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Brand brand)
        {
            string WebRootPath = _webHostEnvironment.WebRootPath;
            var file = HttpContext.Request.Form.Files;
            if (file.Count > 0)
            {
                string newFileName = Guid.NewGuid().ToString();
                var upload = Path.Combine(WebRootPath, @"images\brand");
                var extention = Path.GetExtension(file[0].FileName);

                // Delete old file if it exists
                var objFromDb = await _UnitOfWork.Brand.GetByIdAsync(brand.Id);

                if(objFromDb.BrandLogo != null)
                {
                    var oldImagePath = Path.Combine(WebRootPath, objFromDb.BrandLogo.Trim('\\'));
                    if (System.IO.File.Exists(oldImagePath))
                    {
                        System.IO.File.Delete(oldImagePath);
                    }
                }

                using (var fileStream = new FileStream(Path.Combine(upload, newFileName + extention), FileMode.Create))
                {
                    file[0].CopyTo(fileStream);
                }
                brand.BrandLogo = @"\images\brand\" + newFileName + extention;
            }
            if (ModelState.IsValid)
            {
                var objFromDb = await _UnitOfWork.Brand.GetByIdAsync(brand.Id);
                objFromDb.Name = brand.Name;
                objFromDb.EstablishedYear = brand.EstablishedYear;
                if (brand.BrandLogo != null) 
                {
                    objFromDb.BrandLogo = brand.BrandLogo;
                }
                else
                {
                    objFromDb.BrandLogo = objFromDb.BrandLogo; // Keep the old logo if no new one is provided
                }
                await _UnitOfWork.Brand.Update(brand);
                await _UnitOfWork.SaveAsync();
                TempData["Warning"] = CommonMessage.RecordUpdated;
                return RedirectToAction(nameof(Index));
            }
            return View(brand);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            Brand brand = await _UnitOfWork.Brand.GetByIdAsync(id);
            if (brand == null)
            {
                return NotFound();
            }
            return View(brand);
        }
        [HttpPost]
        public async Task<IActionResult> Delete(Brand brand)
        {
            string WebRootPath = _webHostEnvironment.WebRootPath;
            if(!string.IsNullOrEmpty(brand.BrandLogo))
            {
                // Delete old file if it exists
                var objFromDb = await _UnitOfWork.Brand.GetByIdAsync(brand.Id);

                if (objFromDb.BrandLogo != null)
                {
                    var oldImagePath = Path.Combine(WebRootPath, objFromDb.BrandLogo.Trim('\\'));
                    if (System.IO.File.Exists(oldImagePath))
                    {
                        System.IO.File.Delete(oldImagePath);
                    }
                }

            }
            await _UnitOfWork.Brand.Delete(brand);
            await _UnitOfWork.SaveAsync();
            TempData["Error"] = CommonMessage.RecordDeleted;
            return RedirectToAction(nameof(Index));
        }
    }
}

Hendry_Auto.Web/Views/Shared/_Layout.cshtml
@using Hendry_Auto.Application.ApplicationConstants
@{
    string[] roles = { CustomRole.MasterAdmin, CustomRole.Admin};
    bool isInMultipleRoles = roles.Any(role => User.IsInRole(role));
}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Hendry_Auto.Web</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Hendry_Auto.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.datatables.net/2.3.2/css/dataTables.dataTables.css" />

    
</head>
<body>
    <partial name="_Notification" />
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="Customer" asp-controller="Home" asp-action="Index">Hendry_Auto.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (isInMultipleRoles)
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Content Management</a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li class="nav-item">
                                        <a class="dropdown-item text-dark" asp-area="Admin" asp-controller="Brand" asp-action="Index">Brand</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item text-dark" asp-area="Admin" asp-controller="VehicleType" asp-action="Index">Vehicle Type</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item text-dark" asp-area="Admin" asp-controller="Post" asp-action="Index">Post</a>
                                    </li>
                                </ul>
                            </li>
                        }
                        
                    </ul>

                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Hendry_Auto.Web - <a asp-area="Customer" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" type="text/css" />
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" type="text/javascript"></script>
    <script src="https://cdn.datatables.net/2.3.2/js/dataTables.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Hendry_Auto.Web/Views/Shared/_Notification.cshtml
@if (TempData["Success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" type="text/javascript"></script>

    <script type="text/javascript">
                toastr.options = {
          "closeButton": true,
          "debug": false,
          "newestOnTop": false,
          "progressBar": true,
          "positionClass": "toast-bottom-right",
          "preventDuplicates": false,
          "onclick": null,
          "showDuration": "300",
          "hideDuration": "1000",
          "timeOut": "5000",
          "extendedTimeOut": "1000",
          "showEasing": "swing",
          "hideEasing": "linear",
          "showMethod": "fadeIn",
          "hideMethod": "fadeOut"
        }
        toastr.success('@TempData["Success"]');
    </script>
}

@if (TempData["Warning"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" type="text/javascript"></script>

    <script type="text/javascript">
                toastr.options = {
          "closeButton": true,
          "debug": false,
          "newestOnTop": false,
          "progressBar": true,
          "positionClass": "toast-bottom-right",
          "preventDuplicates": false,
          "onclick": null,
          "showDuration": "300",
          "hideDuration": "1000",
          "timeOut": "5000",
          "extendedTimeOut": "1000",
          "showEasing": "swing",
          "hideEasing": "linear",
          "showMethod": "fadeIn",
          "hideMethod": "fadeOut"
        }
        toastr.warning('@TempData["Warning"]');
    </script>
}


@if (TempData["Error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" type="text/javascript"></script>

    <script type="text/javascript">
                toastr.options = {
          "closeButton": true,
          "debug": false,
          "newestOnTop": false,
          "progressBar": true,
          "positionClass": "toast-bottom-right",
          "preventDuplicates": false,
          "onclick": null,
          "showDuration": "300",
          "hideDuration": "1000",
          "timeOut": "5000",
          "extendedTimeOut": "1000",
          "showEasing": "swing",
          "hideEasing": "linear",
          "showMethod": "fadeIn",
          "hideMethod": "fadeOut"
        }
        toastr.error('@TempData["Error"]');
    </script>
}